# Generated by Django 4.2.7 on 2023-12-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='titulo'),
        ),
    ]
